// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cargo-m/internal/api"
	"cargo-m/internal/config"
	"cargo-m/internal/core"
	"cargo-m/internal/proxy"
	"cargo-m/internal/repository"
	"cargo-m/internal/service"
	"cargo-m/internal/tasks"
)

// Injectors from wire.go:

func InitializeApp() *core.Application {
	applicationConfig := config.LoadApplicationConfig()
	mavenRepo := repository.NewMavenRepo()
	mavenService := service.NewMavenService(mavenRepo, applicationConfig)
	cronTask := tasks.NewCronTask(mavenService, applicationConfig)
	mavenRepoHandler := api.NewMavenRepoHandler(mavenService)
	engine := api.NewRouter(mavenRepoHandler)
	socksProxy := proxy.NewSocksProxy()
	application := core.NewApplication(applicationConfig, cronTask, engine, socksProxy)
	return application
}
