// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cargo-m/internal/api"
	"cargo-m/internal/repository"
	"cargo-m/internal/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeApp() *gin.Engine {
	mavenRepo := repository.NewMavenRepo()
	mavenService := service.NewMavenService(mavenRepo)
	mavenRepoHandler := api.NewMavenRepoHandler(mavenService)
	engine := api.NewRouter(mavenRepoHandler)
	return engine
}
